Spring:
  datasource:
    #url: jdbc:h2:file:F:/workspace/data/beveragedb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    url: jdbc:h2:mem:beveragedb
    driver-class-name: org.h2.Driver
    username: sa
    password: mypass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    web: info
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

management:
  server:
    servlet:
      context-path: /bevarage
server:
  port: 9090
  error:
    whitelabel:
      enabled: false



